name: Kubernetes Deployment

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
    
jobs:

  build:

    runs-on: ubuntu-latest
    env:
      DOCKER_REPOSITORY: blazejop
      IMAGE_NAME: nodemetrics
      IMAGE_TAG: ${{ github.run_number }}
      
    steps:
    - name: Git Checkout
      uses: actions/checkout@v3
    - name: Build Docker Image
      run: docker build . --file Dockerfile --tag $DOCKER_REPOSITORY/$IMAGE_NAME:$GITHUB_RUN_NUMBER
    - name: Login to Docker Hub
      run: |
        echo "${{ secrets.DOCKER_REGISTRY_PASSWORD }}" | docker login -u $DOCKER_REPOSITORY --password-stdin
    - name: Push Image to Repository
      run:
        docker push $DOCKER_REPOSITORY/$IMAGE_NAME:$GITHUB_RUN_NUMBER
    - name: Create Kubeconfig
      run: |
        mkdir ${HOME}/.kube
        echo "${{ secrets.KUBE_CONFIG }}" | base64 --decode > ${HOME}/.kube/config
        cat ${HOME}/.kube/config
    - name: Use Context
      run: kubectl config use-context blaze
    - name: Create Grafana Credentials
      run: |
        echo -n "${{ secrets.GRAFANA_LOGIN }}" > ./admin-user
        echo -n "${{ secrets.GRAFANA_PASSWORD }}" > ./admin-password
        kubectl create secret generic grafana-admin-credentials --from-file=./admin-user --from-file=admin-password --dry-run=client -o yaml > grafana.yaml
        kubectl apply -f grafana.yaml
    - name: Add Prometheus Repository to Helm
      run: |
        helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
        helm repo update
    - name: Helm Upgrade
      run: helm upgrade --install -n blaze prometheus prometheus-community/kube-prometheus-stack -f /home/runner/work/nodemetrics/nodemetrics/manifests/values.yaml
    - name: Deploy to K3S
      run: kubectl apply -f /home/runner/work/nodemetrics/nodemetrics/manifests/nodemetrics.yaml
